// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class CategoryGame
    {
        public int CategoryId { get; set; }
        public int GameId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Game Game { get; set; }
    }
}