// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class CustomerFavorite
    {
        public int CustomerId { get; set; }
        public int GameId { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Game Game { get; set; }
    }
}