// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class Game
    {
        public Game()
        {
            CategoryGame = new HashSet<CategoryGame>();
            CustomerFavorite = new HashSet<CustomerFavorite>();
            CustomerGame = new HashSet<CustomerGame>();
            Media = new HashSet<Media>();
            Order = new HashSet<Order>();
            PlataformGame = new HashSet<PlataformGame>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string ThumbnailLink { get; set; }
        public string BackgroundLink { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public string Requirements { get; set; }
        public DateTime LaunchDate { get; set; }
        public string Developer { get; set; }
        public string Rating { get; set; }
        public string Publisher { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<CategoryGame> CategoryGame { get; set; }
        public virtual ICollection<CustomerFavorite> CustomerFavorite { get; set; }
        public virtual ICollection<CustomerGame> CustomerGame { get; set; }
        public virtual ICollection<Media> Media { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<PlataformGame> PlataformGame { get; set; }
    }
}