// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class Invite
    {
        public Guid Id { get; set; }
        public string Email { get; set; }
        public int AccessLevelId { get; set; }
        public DateTime RequestDate { get; set; }
    }
}