// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class Media
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Link { get; set; }
        public int GameId { get; set; }

        public virtual Game Game { get; set; }
    }
}