// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace OurGames.Core.Model.Model
{
    public partial class PasswordRequest
    {
        public Guid Id { get; set; }
        public DateTime RequestDate { get; set; }
        public int CustomerId { get; set; }

        public virtual Customer Customer { get; set; }
    }
}