export { default as Home } from './Home';
export { default as Games } from './Games';
export { default as CreateAndEditGame } from './CreateAndEditGame';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Admins } from './Admins';
export { default as Library } from './Library';
export { default as Suport } from './Suport';
export { default as Game } from './Game';
